### ISSUE TITLE
Add more info about filtered reads

### ISSUE THREAD

**Issue by khdusenbury** [jbloomlab/alignparse#36]
It would be helpful to have additional information about filtered reads. I was thinking of adding a column with the ``cs`` tag of the feature that failed the filter to the 'filtered' dataframe. This can at least help users see if all reads failing a particular filter are failing for the same reason.

**Comment by jbloom** [comment]
@khdusenbury: This seems reasonable to me. You could either make it happen by default or add an optional parameter to do this.

**Comment by khdusenbury** [comment]
Closed with merging of pull request 38.
