### ISSUE TITLE
Specify `.csv` name in `parse_alignment`

### ISSUE THREAD

**Issue by khdusenbury** [jbloomlab/alignparse#37]
Right now, if you want to output the aligned and filtered reads to `.csv`, the files are given a default name of the form `target_aligned.csv`. If there are multiple runs with the same targets, the files for each run will have the same names. If `to_csv` is used, the user should be able to specify the file name to keep track of which run the reads came from.

**Comment by jbloom** [comment]
@khdusenbury: There is a `csv_dir` that can specify the output directory. Does this work---just specify different directories for each run? Or maybe `align_and_parse` automatically handles this case?

We can add names too, but is it necessary or do we think output directories is sufficient?

**Comment by khdusenbury** [comment]
Ah yes, didn't catch that. Different output directories for each run should be fine! I'll close the issue.
