### ISSUE TITLE
LASV example targets / parse specs

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/alignparse#43]
In the Lassa virus docs, I found it confusing how the explanation of the parse specs and the targets was interspersed. You first discuss the parse specs, but then show the targets before showing the YAML. Maybe the order of this could be simplified by first doing all of the targets stuff and then doing all of the parse specs stuff?

**Comment by khdusenbury** [comment]
I now modeled the organization more off of the other notebooks (where we look at the Genbank file, then discuss the parse specs, then look at the targets plots). I think it's better? 

Let me know what you think.

**Comment by jbloom** [comment]
Looks good to me.
