### ISSUE TITLE
add `mybinder` link to examples

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/alignparse#44]
In the Examples page in the docs, add a link the notebooks on `mybinder`. Here is an [example from dms_variants](https://github.com/jbloomlab/dms_variants/blob/master/docs/examples.rst) of how to do this so it looks like [this](https://jbloomlab.github.io/dms_variants/examples.html) when rendered.

**Comment by khdusenbury** [comment]
Not super familiar with `mybinder`, but I think this now works.
