### ISSUE TITLE
expand README

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/alignparse#45]
Maybe expand the main package README to have a short summary similar to that found on the index page of the docs.

Right now the [README](https://github.com/jbloomlab/alignparse/tree/docs) is very bare-bones compared to the [docs index](https://github.com/jbloomlab/alignparse/blob/docs/docs/index.rst).

**Comment by khdusenbury** [comment]
Added a short description. Not much, but I think it might be sufficient. Let me know if I should add more.

**Comment by jbloom** [comment]
Looks good to me.
