### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/alignparse#46]
@khdusenbury, I looked at the [JOSS manuscript submission instructions](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements), and I have the following suggestions to build on your progress so far:

1. First let's finish the docs, merge the `docs` branch, and make the stable version 0.1.0 of the package. That way the `docs` branch isn't mixing the paper and the documentation writing. 

2. Then let's make a new `paper` branch and finish the JOSS manuscript in that.

3. I think the JOSS manuscript should go in its own subdirectory of the repo with a README etc; maybe this could be a `./paper/` subdirectory or something.

4. Based on your current paper draft, I think it should be much more tailored to describe the specific application. Right now I think it focuses too much on general long-read sequencing. Our package definitely is *not* useful for standard uses of long-read sequencing like genome assembly: it is for the specific case of amplicons with defined features that need to be separated and analyzed. You sort of make this point, but not clearly and quickly enough. Make it much clearer the exact need it is filling: parsing complex sets of features from long sequences. I also definitely suggest splitting into sections, and describing specific uses cases (like barcoded DMS, where you can link to existing Shendure lab papers) and single-cell virus sequencing (where you can link to our paper). Also obviously link the examples and key parts of the API in the paper similar to the example.

Do you want to work along these lines and then maybe we can meet in person to revise?

**Comment by khdusenbury** [comment]
All of this sounds good. I moved the `paper.md` out of the docs branch and will add it back in to its own directory once we finish the docs. 

I'll work on the docs this morning and then probably work on the paper tomorrow, so I should have better drafts of everything by Monday morning. It looks like you're free in the morning. I'd be happy to meet as early as 8:30 am if that works for you?

**Comment by jbloom** [comment]
Pull request #49 adds paper in `./paper/` subdirectory.
