### ISSUE TITLE
dependencies for mybinder

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/alignparse#47]
@khdusenbury: 

The `environment.yml` file has to have all of the dependencies used by the Jupyter notebooks. Ones that are also required by `alignparse` in `setup.py` will automatically be installed, but anything else used by the notebooks needs to be specified in `environment.yml`. For our notebooks, that is the `dms_variants` package.

So in `environment.yml`, underneath [this line](https://github.com/jbloomlab/alignparse/blob/docs/environment.yml#L16) add:
```
- dms_variants>=0.4.1
```

You can then confirm it works by going to `mybinder` and running the notebooks. Right now, the link you have in the examples won't work as it points to the `master` branch -- but that is fine, we want to keep it pointing to `master` as soon we'll merge `docs` into `master`. But confirm the `mybinder` works by going to the link for `docs`, which is:
https://mybinder.org/v2/gh/jbloomlab/alignparse/docs?filepath=notebooks

After you've done this, perhaps the docs branch is done? If you think it is then all done (except for the paper, increment the version in the `CHANGELOG` and `dms_variants/__init__.py` to `0.1.0` and submit a pull request to merge `docs` into `master`.

**Comment by khdusenbury** [comment]
Looks like I got `mybinder` working. Incremented version and submitting pull request.
