### ISSUE TITLE
YAML + FASTA or YAML only input files

### ISSUE THREAD

**Issue by afrubin** [jbloomlab/alignparse#53]
After running the examples, it doesn't seem like there's any information in the Genbank files that couldn't be included in the YAML file. This would be more straightforward for users who are unfamiliar with the Genbank Flat File format and/or don't have the tools to generate these files.

Two options would be to continue to require two input files, but accept the sequence as a FASTA file instead of Genbank, or to allow the user to include the sequence in the YAML file itself.

This would be especially welcome because I didn't see anything in the `alignparse` documentation about how to generate the Genbank file. Some example code or a link to the relevant documentation elsewhere (Biopython?) should be added.

**Comment by khdusenbury** [comment]
First, thank you for your thorough and quick review!

After looking into it a bit, I think support for different file formats for the input sequences may have to be a later feature. I added more info about the GenBank format and how to generate these files to both the paper and the documentation in the latest commits in my pull request. Hopefully, this will make the package easier to use for users that are less familiar with this file format.

**Comment by khdusenbury** [comment]
Added additional info on GenBank format in PR #59. 

Support for different file formats may be a future feature.
