### ISSUE TITLE
Support for compressed input files

### ISSUE THREAD

**Issue by afrubin** [jbloomlab/alignparse#55]
The API documentation says that gzip-compressed input files can be used, but this isn't mentioned in the manuscript or higher-level docs. This is a really nice convenience feature that should be mentioned in a more accessible place, possibly featured in one of the examples.

The tests don't seem to include compressed input files (I only saw uncompressed FASTQ), and these tests should be added if this is a supported feature.

**Comment by khdusenbury** [comment]
I added mention of this feature to the paper and gzipped the LASV input FASTQ file to highlight this. 

I did not change any of the tests, but could do this if this functionality should be tested outside of simply having it in the examples. @jbloom, perhaps we could discuss the best way to do this if needed?

**Comment by khdusenbury** [comment]
Added example with compressed input in PR #59.
