### ISSUE TITLE
Lassa virus example/other aligners in manuscript

### ISSUE THREAD

**Issue by afrubin** [jbloomlab/alignparse#56]
The first question I had after reading the paper was whether I could use alignments that are already generated. This is answered nicely by the [Lassa virus example](https://jbloomlab.github.io/alignparse/lasv_pilot.html) in the documentation, but this isn't in the paper itself. I think the paper would benefit from mentioning this capability explicitly and referencing this example.

**Comment by khdusenbury** [comment]
Added info about this in the paper under `How alignparse works`. Hopefully it makes sense!

**Comment by khdusenbury** [comment]
Implemented in PR #59.
