### ISSUE TITLE
PySAM problems with Python 3.8 + OS X

### ISSUE THREAD

**Issue by bede** [jbloomlab/alignparse#58]
`pip install alignparse` fails for me inside a clean MacOS 10.14 + Python 3.8 environment created with conda due to a PySAM build issue. Using Python 3.7 or else installing pysam with conda in 3.8 works just fine.

Quite likely to be a Mac only issue that will be resolved in a future pysam update, but you could consider [creating an evironment.yml](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) to allow conda to users to install prebuilt dependencies via
`conda env create -f environment.yml`

Edit: conda would also allow managed installation of minimap2

**Comment by khdusenbury** [comment]
We have an `environment.yml` file in the main repo that I think should work for this. It specifies using Python 3.6 to avoid the issues with pysam. I just tested creating the environment locally on my machine and it seemed to work, but let me know if you run into issues! Thanks for your quick review, @bede!

**Comment by jbloom** [comment]
@khdusenbury: Maybe we should also update the docs on installation to say that `alignparse` *requires* Python 3.6 or higher, and is currently tested on Python 3.6 and 3.7. It should work on 3.8 (except for the `pysam` issues which are outside our purview), but right now the Travis tests only run for 3.6 and 3.7.

**Comment by khdusenbury** [comment]
Implemented in PR #59.

**Comment by afrubin** [comment]
> @khdusenbury: Maybe we should also update the docs on installation to say that `alignparse` _requires_ Python 3.6 or higher, and is currently tested on Python 3.6 and 3.7. It should work on 3.8 (except for the `pysam` issues which are outside our purview), but right now the Travis tests only run for 3.6 and 3.7.

Just wanted to point out that the README still has the old language ("requires Python 3.6 or 3.7").

**Comment by jbloom** [comment]
@afrubin: Good point. I've created a pull request for @khdusenbury to review that should address this issue (pull request #60).
