### ISSUE TITLE
What do  {'spacer', 'termini3', 'gene', 'termini5'} each represent?

### ISSUE THREAD

**Issue by xguse** [jbloomlab/alignparse#82]
Forgive me if I missed it on the doc site, but the only places I see these mentioned are in the notebook examples and those take for granted that the person either already has amplicon files made for them or that they know what these are so that they can correctly make their own amplicon genbank files.

Is there a place that you can point me to that provides documentation regarding their definitions and how I should make sure that what I end up labeling as these things in my files are what your software will be expecting them to be?

**Comment by jbloom** [comment]
These are arbitrary. You can have features named anything you want in your Target. For our work, these are typical features, but could be anything else and nothing special about these names.
