### ISSUE TITLE
MyBinder Connection Failed

### ISSUE THREAD

**Issue by greenkidneybean** [jbloomlab/alignparse#83]
Hey!  I'm having trouble getting the Jupyter notebooks to run on MyBinder, it seems to be a connection error (screenshot attached).  Is this working for you guys?

![image](https://user-images.githubusercontent.com/9803586/117014255-a19b3800-acbe-11eb-87b6-c3a5705f189c.png)

I did try a [different notebook](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwipqtTplbDwAhXMElkFHeHKDewQFjAAegQIAhAD&url=https%3A%2F%2Fmybinder.org%2Fv2%2Fgh%2Fbinder-examples%2Fdemo-julia%2Fmaster%3Ffilepath%3Ddemo.ipynb&usg=AOvVaw2GywQ1z9BQtH6J1LCPbGEF) on MyBinder and that's able to run

**Comment by jbloom** [comment]
This should work now. I just had outdated Python version in `environment.yml`.

**Comment by greenkidneybean** [comment]
Thanks @jbloom!
