### ISSUE TITLE
f"string=" issue

### ISSUE THREAD

**Issue by Jayaos** [jbloomlab/alignparse#96]
Thank you for maintaining wonderful package. 

I found out that the codes include f"variable=" expression in utils.py, which is available in python 3.8 or higher. But the installation document says it requires Python 3.7 or higher and is currently tested on Python 3.9. I think the codes need to be modified to general formatting (e.g., .format() or dependency information should be updated to python >= 3.8. 

Thank you so much.

**Comment by jbloom** [comment]
f-strings are supposed to be introduced into Python by version 3.6: https://realpython.com/python-f-strings/

Are you sure this is failing in 3.7?

**Comment by Jayaos** [comment]
f-strings works in python 3.7 but f-string with = specifier ( f"variable=") is new in python 3.8 (https://docs.python.org/3/whatsnew/3.8.html). I modified the line has  f-string with = specifier in utils.py and the package worked fine on my end.
