### ISSUE TITLE
possible bug with indel consensus?

### ISSUE THREAD

**Issue by tylernstarr** [jbloomlab/alignparse#98]
I found a potential bug with alignparse's calling of consensus mutations (here, pertaining to an indel). I have attached a reduced table of ccs's (debugging_ccs.csv) and jupyter notebook (alignparse_bug.md) that demonstrate the problem alongside a different consensus variant with an indel that is being properly handled, for reference. I was able to reduce the default max_indel_diffs parameter to 1 to deal with my specific issue, but it made me wonder if this was a more general issue to be addressed.

In the attachments, I am trying to call a consensus variant for the barcode TCTCAATTAAGAAAAA, which has two ccs reads that agree on the point mutations as well as the presence of an insertion at residue 349, but one ccs annotates the insertion as 12 nt and the other has an additional 13th nt.

When I run simple_mutconsensus with default parameters, I get a consensus sequence for this barcode that contains all of the point mutations, but *no* indel at all, misleadingly looking like it's a shorter-length variant.

My interpretation of where this is going wrong is: when there are 2 ccs, if an indel (and I worry whether the same thing happens with a point mutant?) is present in only one of the two variants, it is not a consensus indel because it is not present in >50% of ccs. In this case, therefore, neither of these 2 ccs have a consensus indel, as there is no consensus on this ins349 identity among the 2 ccs. What goes wrong is that if neither of these conflicting ins349 insertions are consensus, they should be treated as minor indels, and they're each present at >0.25 frequency so per the max_minor_indel_frac=0.25 default parameter, this barcode should be dropped as an unresolvable consensus -- but this is evidently not happening!

My fix was to set max_indel_diffs=1, which then should discard this variant from consensus calling because the two ccs's have a total of 2 indel differences from one another. But, this shouldn't be the ideal way to eliminate this type of barcode from consensus calling and seems to point to something wrong occuring when either or both situations are at play in terms of there being exactly 2 ccs's (so a consensus shoudl require that both ccs are in complete agreement), or something wrong with indel QCing.
[debugging_ccs.csv](https://github.com/jbloomlab/alignparse/files/13480157/debugging_ccs.csv)
[alignparse_bug.md](https://github.com/jbloomlab/alignparse/files/13480211/alignparse_bug.md)

**Comment by jbloom** [comment]
I assume this is using the `simple_mutconsensus` method? I agree that what you say is the current behavior. This method does not work by building an alignment and calling identities: it simply asks "is a specific mutation present in >50% (or some threshold) of the CCS."

You could tweak options (such as as by setting `max_minor_greater_or_equal=True`) so that it returns no consensus here.

But the approach of calling consensus on the mutations is going to fail for your example, as that approach doesn't know that the indels are mostly the same.

I think to fix this would require a substantially more complex method to call consensus sequences, which I'm not sure exists short of building actual alignments of the CCSs?

**Comment by tylernstarr** [comment]
Yeah, I agree it's a difficult consensus to handle, but I guess my question in its basic form is -- why wasn't this barcode eliminated with the default setting of max_minor_indel_frac = 0.25?

My understanding of this parameter is that it is saying, if 25% or more of sequences have an indel that differs from the consensus sequence, it is to be eliminated.

In this case, there are two instances where a minor indel is present in 50% of sequences, greater than the 25% setting. Shouldn't that flag this barcode for elimination?

**Comment by tylernstarr** [comment]
Oh, I think I see now. I was missing the "ceiling" note on the `max_minor_greater_or_equal` option description, and so assumed toggling True or False the `max_minor_greater_or_equal` was only changing whether it was >0.25 or >=0.25, whereas in reality in this case it's determining whether ceiling of 0.25*2 ccs = 1 ccs is inclusive or not for dropping.

**Comment by tylernstarr** [comment]
In that case, I agree setting `max_minor_greater_or_equal=True` gives desired behavior and for the intended logic (whereas setting `max_indel_diffs` to 1 works in this one test case but not for the "right" reason)
