### ISSUE TITLE
Probably a bug in minimap2 error handling?

### ISSUE THREAD

**Issue by jianfcpku** [jbloomlab/alignparse#99]
Line 262 in `minimap2.py`
```python
with contextlib.ExitStack() as stack:
    sam = stack.enter_context(open(untagged_samfile, "w"))
    err = stack.enter_context(tempfile.TemporaryFile(mode="w"))  ----------Line 251
    try:
        _ = subprocess.check_call(cmds, stdout=sam, stderr=err)
    except Exception as exc:
        if os.path.isfile(untagged_samfile):
            os.remove(untagged_samfile)
        exc_type = type(exc).__name__
        err.seek(0)
        raise RuntimeError(
            f"Error running commands:\n{cmds}\n\n"
            f"Exception:\n{exc_type}: {exc}\n\n"
            f"Error message:\n{err.read()}\n\n"   --------Line 262
        )
```
The tempfile for errors was created in mode "w" but read during the error handling. This will cause `io.UnsupportedOperation: not readable`. Maybe the mode should be changed to "w+".

**Comment by jbloom** [comment]
Good catch on this error, @jianfcpku. I agree that it appears that the mode should be changed to `w+` here.

Are you making a pull request to do this, or do you want me to just make the change? (Either is fine by me).

**Comment by jianfcpku** [comment]
Thanks for fast reply! I have created a pull request.
